import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { AuthProvider } from "@/providers/AuthProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import clsx from "clsx";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <AuthProvider>
        <body
          className={clsx(
            `${inter.className}`,
            "overflow-x-hidden flex flex-col h-screen "
          )}
        >
          <ThemeProvider>
            <Header />
            <main className="flex-1">
              <Toaster richColors duration={10000} />
              {children}
            </main>
          </ThemeProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
